project_name := "mkSingleChecker3_null_SingleChecker3_design"
dut := "mkSingleChecker3_null"

default:
    @just --list

synth:
    cd ../../../ && make ./build/verilog/{{dut}}.v
    make ./output_files/{{project_name}}.sta.rpt

force-synth:
    cd ../../../ && make ./build/verilog/{{dut}}.v
    quartus_sh --flow compile {{project_name}}

force-synth-seeds:
    cd ../../../ && make ./build/verilog/{{dut}}.v
    quartus_sh -t ../../compile_revisions.tcl {{project_name}} 

reports:
    grep -B 1 -A 6 "; Fmax Summary" output_files/{{project_name}}.sta.rpt
    grep -B 1 -A 90 "; Fitter Resource Usage Summary" output_files/{{project_name}}.fit.place.rpt

gui:
    quartus {{project_name}}.qpf &

clean:
    rm -rf ./output_files/
    rm -rf ./qdb/

