
// Generated by gen_design.py from SingleChecker3.txt
// Expects mkSingleChecker3_2percycle to fit the SingleChecker3 Bluespec interface
module mkSingleChecker3_2percycle_SingleChecker3_design(
    input CLK_SLOW,
    input CLK_FAST,
    input RST_N,
    input pin_in,
    output pin_out
);
    wire[566-1:0] dut_in;
    wire[256-1:0] dut_out;
    assign dut_out[255:179] = 0;
    
    input_harness#(.BITS(566)) i(
        .slow_clk(CLK_SLOW),
        .fast_clk(CLK_FAST),
        .rst_n(RST_N),
        .pin_on_slow_clk(pin_in),
        .data_on_fast_clk(dut_in)
    );

    output_harness#(.BITS(256), .LG_BITS(8)) o(
        .slow_clk(CLK_SLOW),
        .fast_clk(CLK_FAST),
        .rst_n(RST_N),
        .data_on_fast_clk(dut_out),
        .pin_on_slow_clk(pin_out)
    );

    mkSingleChecker3_2percycle dut(
        .CLK(CLK_FAST),
        .RST_N(RST_N),

        .checker_in_put_val(dut_in[553:0]),
        .checker_keyToKill__write_x(dut_in[562:554]),
        .EN_checker_checkResponse_drop(dut_in[563]),
        .EN_checker_in_put(dut_in[564]),
        .EN_checker_keyToKill__write(dut_in[565]),
        .checker_checkResponse_peek_snd_fst(dut_out[63:0]),
        .checker_checkResponse_peek_snd_snd_fst(dut_out[71:64]),
        .checker_checkResponse_peek_fst(dut_out[168:72]),
        .checker_checkResponse_canPeek(dut_out[169]),
        .checker_checkResponse_peek_snd_snd_snd(dut_out[170]),
        .checker_in_canPut(dut_out[171]),
        .RDY_checker_checkResponse_drop(dut_out[172]),
        .RDY_checker_checkResponse_peek_fst(dut_out[173]),
        .RDY_checker_checkResponse_peek_snd_fst(dut_out[174]),
        .RDY_checker_checkResponse_peek_snd_snd_fst(dut_out[175]),
        .RDY_checker_checkResponse_peek_snd_snd_snd(dut_out[176]),
        .RDY_checker_in_put(dut_out[177]),
        .RDY_checker_keyToKill__write(dut_out[178])
    );
endmodule

