
// Generated by gen_design.py from UnifiedSingleExposerKeyMngrTb.txt
// Expects mkCombinedIOCapExposerV6_blockinvalid_2pool_1percycle_KeyManager2V1_Tb to fit the UnifiedSingleExposerKeyMngrTb Bluespec interface
module mkCombinedIOCapExposerV6_blockinvalid_2pool_1percycle_KeyManager2V1_Tb_UnifiedSingleExposerKeyMngrTb_design(
    input CLK_SLOW,
    input CLK_FAST,
    input RST_N,
    input pin_in,
    output pin_out
);
    wire[365-1:0] dut_in;
    wire[512-1:0] dut_out;
    assign dut_out[511:349] = 0;
    
    input_harness#(.BITS(365)) i(
        .slow_clk(CLK_SLOW),
        .fast_clk(CLK_FAST),
        .rst_n(RST_N),
        .pin_on_slow_clk(pin_in),
        .data_on_fast_clk(dut_in)
    );

    output_harness#(.BITS(512), .LG_BITS(9)) o(
        .slow_clk(CLK_SLOW),
        .fast_clk(CLK_FAST),
        .rst_n(RST_N),
        .data_on_fast_clk(dut_out),
        .pin_on_slow_clk(pin_out)
    );

    mkCombinedIOCapExposerV6_blockinvalid_2pool_1percycle_KeyManager2V1_Tb dut(
        .CLK(CLK_FAST),
        .RST_N(RST_N),

        .keyStore_ar_put_val(dut_in[15:0]),
        .keyStore_aw_put_val(dut_in[31:16]),
        .keyStore_w_put_val(dut_in[67:32]),
        .exposer4x32_iocapsIn_axiSignals_w_put_val(dut_in[104:68]),
        .exposer4x32_sanitizedOut_r_put_val(dut_in[143:105]),
        .exposer4x32_sanitizedOut_b_put_val(dut_in[149:144]),
        .exposer4x32_iocapsIn_axiSignals_ar_put_val(dut_in[249:150]),
        .exposer4x32_iocapsIn_axiSignals_aw_put_val(dut_in[349:250]),
        .EN_exposer4x32_iocapsIn_axiSignals_ar_put(dut_in[350]),
        .EN_exposer4x32_iocapsIn_axiSignals_aw_put(dut_in[351]),
        .EN_exposer4x32_iocapsIn_axiSignals_b_drop(dut_in[352]),
        .EN_exposer4x32_iocapsIn_axiSignals_r_drop(dut_in[353]),
        .EN_exposer4x32_iocapsIn_axiSignals_w_put(dut_in[354]),
        .EN_exposer4x32_sanitizedOut_ar_drop(dut_in[355]),
        .EN_exposer4x32_sanitizedOut_aw_drop(dut_in[356]),
        .EN_exposer4x32_sanitizedOut_b_put(dut_in[357]),
        .EN_exposer4x32_sanitizedOut_r_put(dut_in[358]),
        .EN_exposer4x32_sanitizedOut_w_drop(dut_in[359]),
        .EN_keyStore_ar_put(dut_in[360]),
        .EN_keyStore_aw_put(dut_in[361]),
        .EN_keyStore_b_drop(dut_in[362]),
        .EN_keyStore_r_drop(dut_in[363]),
        .EN_keyStore_w_put(dut_in[364]),
        .keyStore_b_peek(dut_out[1:0]),
        .keyStore_r_peek(dut_out[35:2]),
        .exposer4x32_sanitizedOut_w_peek(dut_out[72:36]),
        .exposer4x32_iocapsIn_axiSignals_r_peek(dut_out[111:73]),
        .exposer4x32_iocapsIn_axiSignals_b_peek(dut_out[117:112]),
        .exposer4x32_sanitizedOut_ar_peek(dut_out[214:118]),
        .exposer4x32_sanitizedOut_aw_peek(dut_out[311:215]),
        .exposer4x32_iocapsIn_axiSignals_ar_canPut(dut_out[312]),
        .exposer4x32_iocapsIn_axiSignals_aw_canPut(dut_out[313]),
        .exposer4x32_iocapsIn_axiSignals_b_canPeek(dut_out[314]),
        .exposer4x32_iocapsIn_axiSignals_r_canPeek(dut_out[315]),
        .exposer4x32_iocapsIn_axiSignals_w_canPut(dut_out[316]),
        .exposer4x32_sanitizedOut_ar_canPeek(dut_out[317]),
        .exposer4x32_sanitizedOut_aw_canPeek(dut_out[318]),
        .exposer4x32_sanitizedOut_b_canPut(dut_out[319]),
        .exposer4x32_sanitizedOut_r_canPut(dut_out[320]),
        .exposer4x32_sanitizedOut_w_canPeek(dut_out[321]),
        .keyStore_ar_canPut(dut_out[322]),
        .keyStore_aw_canPut(dut_out[323]),
        .keyStore_b_canPeek(dut_out[324]),
        .keyStore_r_canPeek(dut_out[325]),
        .keyStore_w_canPut(dut_out[326]),
        .RDY_exposer4x32_iocapsIn_axiSignals_ar_put(dut_out[327]),
        .RDY_exposer4x32_iocapsIn_axiSignals_aw_put(dut_out[328]),
        .RDY_exposer4x32_iocapsIn_axiSignals_b_drop(dut_out[329]),
        .RDY_exposer4x32_iocapsIn_axiSignals_b_peek(dut_out[330]),
        .RDY_exposer4x32_iocapsIn_axiSignals_r_drop(dut_out[331]),
        .RDY_exposer4x32_iocapsIn_axiSignals_r_peek(dut_out[332]),
        .RDY_exposer4x32_iocapsIn_axiSignals_w_put(dut_out[333]),
        .RDY_exposer4x32_sanitizedOut_ar_drop(dut_out[334]),
        .RDY_exposer4x32_sanitizedOut_ar_peek(dut_out[335]),
        .RDY_exposer4x32_sanitizedOut_aw_drop(dut_out[336]),
        .RDY_exposer4x32_sanitizedOut_aw_peek(dut_out[337]),
        .RDY_exposer4x32_sanitizedOut_b_put(dut_out[338]),
        .RDY_exposer4x32_sanitizedOut_r_put(dut_out[339]),
        .RDY_exposer4x32_sanitizedOut_w_drop(dut_out[340]),
        .RDY_exposer4x32_sanitizedOut_w_peek(dut_out[341]),
        .RDY_keyStore_ar_put(dut_out[342]),
        .RDY_keyStore_aw_put(dut_out[343]),
        .RDY_keyStore_b_drop(dut_out[344]),
        .RDY_keyStore_b_peek(dut_out[345]),
        .RDY_keyStore_r_drop(dut_out[346]),
        .RDY_keyStore_r_peek(dut_out[347]),
        .RDY_keyStore_w_put(dut_out[348]),
        .debugKeyState__read(),
        .debugBadRead__read(),
        .debugBadWrite__read(),
        .debugGoodRead__read(),
        .debugGoodWrite__read(),
        .debugEnableKey__read(),
        .debugKillKey__read(),
        .RDY_debugBadRead__read(),
        .RDY_debugBadWrite__read(),
        .RDY_debugEnableKey__read(),
        .RDY_debugGoodRead__read(),
        .RDY_debugGoodWrite__read(),
        .RDY_debugKeyState__read(),
        .RDY_debugKillKey__read()
    );
endmodule

