extern crate cbindgen;

use std::env;

fn main() {
    // Get the crate cbindgen config, and add a version #define
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let mut config = cbindgen::Config::from_root_or_default(&crate_dir);
    assert!(config.header.is_none());
    config.header = Some(format!(r#"/**
* A library for using I/O capabilities with cryptographic protection, a.k.a. crypto-caps, a.k.a. ccaps.
* Generated by cbindgen from the rust_caps_c Rust crate version {}.
*/"#, env::var("CARGO_PKG_VERSION").unwrap()));

    // rerun if Cargo.toml was changed, the version may have changed
    println!("cargo::rerun-if-changed=Cargo.toml");
    println!("cargo::rerun-if-changed=build.rs");

    cbindgen::generate_with_config(crate_dir, config)
        .expect("Unable to generate bindings")
        .write_to_file("librust_caps_c.h");
}