# TCL File Generated by Component Editor 21.3
# Wed Aug 24 11:43:12 BST 2022
# DO NOT MODIFY


# 
# swm_tx_adapter "swm_tx_adapter" v1.0
#  2022.08.24.11:43:12
# 
# 

# 
# request TCL package from ACDS 21.3
# 
package require -exact qsys 21.3


# 
# module swm_tx_adapter
# 
set_module_property DESCRIPTION ""
set_module_property NAME swm_tx_adapter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME swm_tx_adapter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL swm_tx_adapter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file swm_tx_adapter.v VERILOG PATH swm_tx_adapter.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""
set_interface_property clock_sink IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port clock_sink clk_in_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""
set_interface_property reset_sink IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port reset_sink reset_in_rst reset Input 1


# 
# connection point data_tx
# 
add_interface data_tx conduit end
set_interface_property data_tx associatedClock ""
set_interface_property data_tx associatedReset ""
set_interface_property data_tx ENABLED true
set_interface_property data_tx EXPORT_OF ""
set_interface_property data_tx PORT_NAME_MAP ""
set_interface_property data_tx CMSIS_SVD_VARIABLES ""
set_interface_property data_tx SVD_ADDRESS_GROUP ""
set_interface_property data_tx IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port data_tx data_tx tx_data Output 256


# 
# connection point valid_tx
# 
add_interface valid_tx conduit end
set_interface_property valid_tx associatedClock ""
set_interface_property valid_tx associatedReset ""
set_interface_property valid_tx ENABLED true
set_interface_property valid_tx EXPORT_OF ""
set_interface_property valid_tx PORT_NAME_MAP ""
set_interface_property valid_tx CMSIS_SVD_VARIABLES ""
set_interface_property valid_tx SVD_ADDRESS_GROUP ""
set_interface_property valid_tx IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port valid_tx valid_tx tx_valid Output 1


# 
# connection point start_of_burst_tx
# 
add_interface start_of_burst_tx conduit end
set_interface_property start_of_burst_tx associatedClock ""
set_interface_property start_of_burst_tx associatedReset ""
set_interface_property start_of_burst_tx ENABLED true
set_interface_property start_of_burst_tx EXPORT_OF ""
set_interface_property start_of_burst_tx PORT_NAME_MAP ""
set_interface_property start_of_burst_tx CMSIS_SVD_VARIABLES ""
set_interface_property start_of_burst_tx SVD_ADDRESS_GROUP ""
set_interface_property start_of_burst_tx IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port start_of_burst_tx start_of_burst_tx tx_start_of_burst Output 1


# 
# connection point end_of_burst_tx
# 
add_interface end_of_burst_tx conduit end
set_interface_property end_of_burst_tx associatedClock ""
set_interface_property end_of_burst_tx associatedReset ""
set_interface_property end_of_burst_tx ENABLED true
set_interface_property end_of_burst_tx EXPORT_OF ""
set_interface_property end_of_burst_tx PORT_NAME_MAP ""
set_interface_property end_of_burst_tx CMSIS_SVD_VARIABLES ""
set_interface_property end_of_burst_tx SVD_ADDRESS_GROUP ""
set_interface_property end_of_burst_tx IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port end_of_burst_tx end_of_burst_tx tx_end_of_burst Output 1


# 
# connection point error_tx
# 
add_interface error_tx conduit end
set_interface_property error_tx associatedClock ""
set_interface_property error_tx associatedReset ""
set_interface_property error_tx ENABLED true
set_interface_property error_tx EXPORT_OF ""
set_interface_property error_tx PORT_NAME_MAP ""
set_interface_property error_tx CMSIS_SVD_VARIABLES ""
set_interface_property error_tx SVD_ADDRESS_GROUP ""
set_interface_property error_tx IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port error_tx error_tx tx_error Input 4


# 
# connection point ready_tx
# 
add_interface ready_tx conduit end
set_interface_property ready_tx associatedClock ""
set_interface_property ready_tx associatedReset ""
set_interface_property ready_tx ENABLED true
set_interface_property ready_tx EXPORT_OF ""
set_interface_property ready_tx PORT_NAME_MAP ""
set_interface_property ready_tx CMSIS_SVD_VARIABLES ""
set_interface_property ready_tx SVD_ADDRESS_GROUP ""
set_interface_property ready_tx IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port ready_tx ready_tx tx_ready Input 1


# 
# connection point sync_tx
# 
add_interface sync_tx conduit end
set_interface_property sync_tx associatedClock ""
set_interface_property sync_tx associatedReset ""
set_interface_property sync_tx ENABLED true
set_interface_property sync_tx EXPORT_OF ""
set_interface_property sync_tx PORT_NAME_MAP ""
set_interface_property sync_tx CMSIS_SVD_VARIABLES ""
set_interface_property sync_tx SVD_ADDRESS_GROUP ""
set_interface_property sync_tx IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port sync_tx sync_tx tx_sync Output 8


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock_sink
set_interface_property avalon_streaming_sink associatedReset reset_sink
set_interface_property avalon_streaming_sink dataBitsPerSymbol 32
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyAllowance 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""
set_interface_property avalon_streaming_sink IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port avalon_streaming_sink avalonst_sink_data data Input 32
add_interface_port avalon_streaming_sink avalonst_sink_valid valid Input 1
add_interface_port avalon_streaming_sink avalonst_sink_startofpacket startofpacket Input 1
add_interface_port avalon_streaming_sink avalonst_sink_endofpacket endofpacket Input 1
add_interface_port avalon_streaming_sink avalonst_sink_ready ready Output 1

