# TCL File Generated by Component Editor 21.3
# Wed Aug 24 11:41:33 BST 2022
# DO NOT MODIFY


# 
# swm_rx_adapter "swm_rx_adapter" v1.0
#  2022.08.24.11:41:33
# 
# 

# 
# request TCL package from ACDS 21.3
# 
package require -exact qsys 21.3


# 
# module swm_rx_adapter
# 
set_module_property DESCRIPTION ""
set_module_property NAME swm_rx_adapter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME swm_rx_adapter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL swm_rx_adapter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file swm_rx_adapter.v VERILOG PATH swm_rx_adapter.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalonst_source
# 
add_interface avalonst_source avalon_streaming start
set_interface_property avalonst_source associatedClock clock_sink
set_interface_property avalonst_source associatedReset reset_sink
set_interface_property avalonst_source dataBitsPerSymbol 32
set_interface_property avalonst_source errorDescriptor ""
set_interface_property avalonst_source firstSymbolInHighOrderBits true
set_interface_property avalonst_source maxChannel 0
set_interface_property avalonst_source readyAllowance 0
set_interface_property avalonst_source readyLatency 0
set_interface_property avalonst_source ENABLED true
set_interface_property avalonst_source EXPORT_OF ""
set_interface_property avalonst_source PORT_NAME_MAP ""
set_interface_property avalonst_source CMSIS_SVD_VARIABLES ""
set_interface_property avalonst_source SVD_ADDRESS_GROUP ""
set_interface_property avalonst_source IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port avalonst_source avalonst_source_data data Output 32
add_interface_port avalonst_source avalonst_source_valid valid Output 1
add_interface_port avalonst_source avalonst_source_startofpacket startofpacket Output 1
add_interface_port avalonst_source avalonst_source_ready ready Input 1
add_interface_port avalonst_source avalonst_source_endofpacket endofpacket Output 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""
set_interface_property clock_sink IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port clock_sink clk_in_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""
set_interface_property reset_sink IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port reset_sink reset_in_rst reset Input 1


# 
# connection point data_rx
# 
add_interface data_rx conduit end
set_interface_property data_rx associatedClock ""
set_interface_property data_rx associatedReset ""
set_interface_property data_rx ENABLED true
set_interface_property data_rx EXPORT_OF ""
set_interface_property data_rx PORT_NAME_MAP ""
set_interface_property data_rx CMSIS_SVD_VARIABLES ""
set_interface_property data_rx SVD_ADDRESS_GROUP ""
set_interface_property data_rx IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port data_rx data_rx rx_data Input 256


# 
# connection point valid_rx
# 
add_interface valid_rx conduit end
set_interface_property valid_rx associatedClock ""
set_interface_property valid_rx associatedReset ""
set_interface_property valid_rx ENABLED true
set_interface_property valid_rx EXPORT_OF ""
set_interface_property valid_rx PORT_NAME_MAP ""
set_interface_property valid_rx CMSIS_SVD_VARIABLES ""
set_interface_property valid_rx SVD_ADDRESS_GROUP ""
set_interface_property valid_rx IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port valid_rx valid_rx rx_valid Input 1


# 
# connection point start_of_burst
# 
add_interface start_of_burst conduit end
set_interface_property start_of_burst associatedClock ""
set_interface_property start_of_burst associatedReset ""
set_interface_property start_of_burst ENABLED true
set_interface_property start_of_burst EXPORT_OF ""
set_interface_property start_of_burst PORT_NAME_MAP ""
set_interface_property start_of_burst CMSIS_SVD_VARIABLES ""
set_interface_property start_of_burst SVD_ADDRESS_GROUP ""
set_interface_property start_of_burst IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port start_of_burst start_of_burst_rx rx_start_of_burst Input 1


# 
# connection point end_of_burst_rx
# 
add_interface end_of_burst_rx conduit end
set_interface_property end_of_burst_rx associatedClock ""
set_interface_property end_of_burst_rx associatedReset ""
set_interface_property end_of_burst_rx ENABLED true
set_interface_property end_of_burst_rx EXPORT_OF ""
set_interface_property end_of_burst_rx PORT_NAME_MAP ""
set_interface_property end_of_burst_rx CMSIS_SVD_VARIABLES ""
set_interface_property end_of_burst_rx SVD_ADDRESS_GROUP ""
set_interface_property end_of_burst_rx IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port end_of_burst_rx end_of_burst_rx rx_end_of_burst Input 1


# 
# connection point error_rx
# 
add_interface error_rx conduit end
set_interface_property error_rx associatedClock ""
set_interface_property error_rx associatedReset ""
set_interface_property error_rx ENABLED true
set_interface_property error_rx EXPORT_OF ""
set_interface_property error_rx PORT_NAME_MAP ""
set_interface_property error_rx CMSIS_SVD_VARIABLES ""
set_interface_property error_rx SVD_ADDRESS_GROUP ""
set_interface_property error_rx IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port error_rx error_rx rx_error Input 9


# 
# connection point ready_rx
# 
add_interface ready_rx conduit end
set_interface_property ready_rx associatedClock ""
set_interface_property ready_rx associatedReset ""
set_interface_property ready_rx ENABLED true
set_interface_property ready_rx EXPORT_OF ""
set_interface_property ready_rx PORT_NAME_MAP ""
set_interface_property ready_rx CMSIS_SVD_VARIABLES ""
set_interface_property ready_rx SVD_ADDRESS_GROUP ""
set_interface_property ready_rx IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port ready_rx ready_rx rx_ready Output 1


# 
# connection point sync_rx
# 
add_interface sync_rx conduit end
set_interface_property sync_rx associatedClock ""
set_interface_property sync_rx associatedReset ""
set_interface_property sync_rx ENABLED true
set_interface_property sync_rx EXPORT_OF ""
set_interface_property sync_rx PORT_NAME_MAP ""
set_interface_property sync_rx CMSIS_SVD_VARIABLES ""
set_interface_property sync_rx SVD_ADDRESS_GROUP ""
set_interface_property sync_rx IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port sync_rx sync_rx rx_sync Input 8

