import argparse
from dataclasses import dataclass
import glob
from io import StringIO
import math
import os
from pathlib import Path
import re
import sys
from typing import Callable, List, TextIO, Tuple

N_SEEDS = 32
def seed_name(seed: int) -> str:
    return f"Seed{seed:02d}"

SPECIAL_INPUTS = ["CLK", "RST_N"]

INPUT = re.compile(r"input\s+(\[(\d+)\s*:\s*0\]\s+)?(\w+);")
OUTPUT = re.compile(r"output\s+(\[(\d+)\s*:\s*0\]\s+)?(\w+);")

@dataclass
class InterfaceSpec:
    ifc_file: str
    ifc_name: str
    ifc_inputs: List[Tuple[str, int]]
    ifc_outputs: List[Tuple[str, int]]
    ifc_dbg_outputs: List[Tuple[str, int]]
    overall_input_width: int
    # For output that isn't debug
    # ---------------------------
    overall_output_width: int
    # overall_output_width padded to a power of two
    padded_output_width: int
    padded_output_lg2: int
    # For output that is debug
    overall_dbg_output_width: int

    @staticmethod
    def generate(ifc_file_path: str):
        ifc_name = os.path.basename(args.ifc).removesuffix(".txt")
        ifc_inputs = []
        ifc_dbg_outputs = []
        ifc_outputs = []

        # TODO ignore debug signals

        with open(args.ifc, "r") as f:
            for line in f:
                if not line.strip():
                    continue
                input_m = INPUT.match(line)
                if input_m:
                    signal_name = input_m.group(3)
                    if signal_name in SPECIAL_INPUTS:
                        print(f"Ignoring special input {signal_name}", file=sys.stderr)
                        continue
                    width = (int(input_m.group(2)) + 1) if input_m.group(2) is not None else 1
                    ifc_inputs.append((signal_name, width))
                    continue
                output_m = OUTPUT.match(line)
                if output_m:
                    signal_name = output_m.group(3)
                    width = (int(output_m.group(2)) + 1) if output_m.group(2) is not None else 1
                    if "debug" in signal_name:
                        ifc_dbg_outputs.append((signal_name, width))
                    else:
                        ifc_outputs.append((signal_name, width))
                    continue

                raise RuntimeError(f"Line '{line}' doesn't match either input or output")
            
        overall_input_width = sum(w for (name, w) in ifc_inputs)
        overall_output_width = sum(w for (name, w) in ifc_outputs)
        overall_dbg_output_width = sum(w for (name, w) in ifc_dbg_outputs)
        assert overall_input_width != 0
        assert overall_output_width != 0
        
        # https://stackoverflow.com/a/14267825
        padded_output_lg2 = math.ceil(math.log(overall_output_width, 2))
        padded_output_width = 2 ** padded_output_lg2

        return InterfaceSpec(
            ifc_file=ifc_file_path,
            ifc_name=ifc_name,
            ifc_inputs=ifc_inputs,
            ifc_outputs=ifc_outputs,
            ifc_dbg_outputs=ifc_dbg_outputs,
            overall_input_width=overall_input_width,
            overall_output_width=overall_output_width,
            padded_output_width=padded_output_width,
            padded_output_lg2=padded_output_lg2,
            overall_dbg_output_width=overall_dbg_output_width,
        )

def toplevel_verilog(ifc: InterfaceSpec, dut: str, file):
    output_wire_assign = ""
    if ifc.overall_output_width < ifc.padded_output_width:
        output_wire_assign = f"assign dut_out[{ifc.padded_output_width - 1}:{ifc.overall_output_width}] = 0;"

    prefix = f"""
// Generated by gen_design.py from {ifc.ifc_file}
// Expects {dut} to fit the {ifc.ifc_name} Bluespec interface
module {dut}_{ifc.ifc_name}_design(
    input CLK_SLOW,
    input CLK_FAST,
    input RST_N,
    input pin_in,
    output pin_out
);
    wire[{ifc.overall_input_width}-1:0] dut_in;
    wire[{ifc.padded_output_width}-1:0] dut_out;
    {output_wire_assign}
    
    input_harness#(.BITS({ifc.overall_input_width})) i(
        .slow_clk(CLK_SLOW),
        .fast_clk(CLK_FAST),
        .rst_n(RST_N),
        .pin_on_slow_clk(pin_in),
        .data_on_fast_clk(dut_in)
    );

    output_harness#(.BITS({ifc.padded_output_width}), .LG_BITS({ifc.padded_output_lg2})) o(
        .slow_clk(CLK_SLOW),
        .fast_clk(CLK_FAST),
        .rst_n(RST_N),
        .data_on_fast_clk(dut_out),
        .pin_on_slow_clk(pin_out)
    );

    {dut} dut(
        .CLK(CLK_FAST),
        .RST_N(RST_N),
"""
    suffix = f"""
    );
endmodule
"""
    print(prefix, file=file)

    first = True
    curr_input_start_bit = 0
    for (name, width) in ifc.ifc_inputs:
        if not first:
            print(f",", file=file)
        if width == 1:
            print(f"        .{name}(dut_in[{curr_input_start_bit}])", end='', file=file)
        else:
            print(f"        .{name}(dut_in[{curr_input_start_bit+width-1}:{curr_input_start_bit}])", end='', file=file)
        curr_input_start_bit += width
        first = False

    curr_output_start_bit = 0
    for (name, width) in ifc.ifc_outputs:
        if not first:
            print(f",", file=file)
        if width == 1:
            print(f"        .{name}(dut_out[{curr_output_start_bit}])", end='', file=file)
        else:
            print(f"        .{name}(dut_out[{curr_output_start_bit+width-1}:{curr_output_start_bit}])", end='', file=file)
        curr_output_start_bit += width
        first = False

    # Tie off all debug outputs
    for (name, width) in ifc.ifc_dbg_outputs:
        if not first:
            print(f",", file=file)
        print(f"        .{name}()", end='', file=file)
        first = False

    print(suffix, file=file)

def qpf(project_name, file):
# Old non-quartus ones
# set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/BRAM2Load.v"
# set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/BRAM2BELoad.v"
# set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/BRAM2BE.v"
# set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/BRAM2.v"
# set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/BRAM1Load.v"
# set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/BRAM1BELoad.v"
# set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/BRAM1BE.v"
# set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/BRAM1.v"


    contents=f"""
# -------------------------------------------------------------------------- #
#
# Copyright (C) 2023  Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions 
# and other software and tools, and any partner logic 
# functions, and any output files from any of the foregoing 
# (including device programming or simulation files), and any 
# associated documentation or information are expressly subject 
# to the terms and conditions of the Intel Program License 
# Subscription Agreement, the Intel Quartus Prime License Agreement,
# the Intel FPGA IP License Agreement, or other applicable license
# agreement, including, without limitation, that your use is for
# the sole purpose of programming logic devices manufactured by
# Intel and sold by Intel or its authorized distributors.  Please
# refer to the applicable agreement for further details, at
# https://fpgasoftware.intel.com/eula.
#
# -------------------------------------------------------------------------- #
#
# Quartus Prime
# Version 23.2.0 Build 94 06/14/2023 SC Pro Edition
# Date created = 20:50:32  October 16, 2025
#
# -------------------------------------------------------------------------- #

QUARTUS_VERSION = "23.2"
DATE = "20:50:32  October 16, 2025"

# Revisions

PROJECT_REVISION = "{project_name}"
"""
    print(contents, file=file)
    for seed in range(N_SEEDS):
        print(f"PROJECT_REVISION = \"{seed_name(seed)}\"", file=file)

def qsf_from_bluespec(project_name, file, seed=None):
    prefix = f"""
set_global_assignment -name TOP_LEVEL_ENTITY {project_name}
set_global_assignment -name ORIGINAL_QUARTUS_VERSION 23.2.0
set_global_assignment -name PROJECT_CREATION_TIME_DATE "20:50:32  OCTOBER 16, 2025"
set_global_assignment -name LAST_QUARTUS_VERSION "23.2.0 Pro Edition"
set_global_assignment -name VERILOG_FILE "../../verilog/Verilog.Quartus/BRAM2Load.v"
set_global_assignment -name VERILOG_FILE "../../verilog/Verilog.Quartus/BRAM2BELoad.v"
set_global_assignment -name VERILOG_FILE "../../verilog/Verilog.Quartus/BRAM2BE.v"
set_global_assignment -name VERILOG_FILE "../../verilog/Verilog.Quartus/BRAM2.v"
set_global_assignment -name VERILOG_FILE "../../verilog/Verilog.Quartus/BRAM1Load.v"
set_global_assignment -name VERILOG_FILE "../../verilog/Verilog.Quartus/BRAM1BELoad.v"
set_global_assignment -name VERILOG_FILE "../../verilog/Verilog.Quartus/BRAM1BE.v"
set_global_assignment -name VERILOG_FILE "../../verilog/Verilog.Quartus/BRAM1.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/UngatedClockSelect.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/UngatedClockMux.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/TriState.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/SyncWire.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/SyncResetA.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/SyncReset0.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/SyncReset.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/SyncRegister.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/SyncPulse.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/SyncHandshake.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/SyncFIFOLevel0.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/SyncFIFOLevel.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/SyncFIFO10.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/SyncFIFO1.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/SyncFIFO0.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/SyncFIFO.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/SyncBit15.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/SyncBit1.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/SyncBit05.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/SyncBit.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/SizedFIFOL0.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/SizedFIFOL.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/SizedFIFO0.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/SizedFIFO.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/ScanIn.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/SampleReg.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/RWire0.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/RWire.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/RevertReg.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/ResolveZ.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/ResetToBool.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/ResetMux.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/ResetInverter.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/ResetEither.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/RegUN.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/RegTwoUN.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/RegTwoN.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/RegTwoA.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/RegN.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/RegFileLoad.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/RegFile.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/RegAligned.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/RegA.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/ProbeWire.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/ProbeValue.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/ProbeTrigger.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/ProbeMux.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/ProbeHook.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/ProbeCapture.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/McpRegUN.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/MakeResetA.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/MakeReset0.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/MakeReset.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/MakeClock.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/LatchCrossingReg.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/InoutConnect.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/InitialReset.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/GatedClockInverter.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/GatedClockDiv.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/GatedClock.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/Fork.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/FIFOL20.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/FIFOL2.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/FIFOL10.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/FIFOL1.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/FIFO20.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/FIFO2.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/FIFO10.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/FIFO1.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/Empty.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/DualPortRam.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/CrossingRegUN.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/CrossingRegN.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/CrossingRegA.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/CrossingBypassWire.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/CRegUN5.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/CRegN5.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/CRegA5.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/Counter.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/ConvertToZ.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/ConvertFromZ.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/ConstrainedRandom.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/ConfigRegUN.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/ConfigRegN.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/ConfigRegA.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/ClockSelect.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/ClockMux.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/ClockInverter.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/ClockGen.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/ClockDiv.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/BypassWire0.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/BypassWire.v"
set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/BypassCrossingWire.v"
"""
    #set_global_assignment -name VERILOG_FILE "$::env(BLUESPECDIR)/Verilog/main.v"

# set_global_assignment -name VERILOG_FILE ../build/verilog/mkInternalCalc_2024Aes1RoundPerCycleFast.v
# set_global_assignment -name VERILOG_FILE ../build/verilog/mkSimpleIOCapExposerV6_blockinvalid_1percycle_Tb.v
# set_global_assignment -name VERILOG_FILE ../build/verilog/mkInternalCalc_2024Aes2RoundPerCycleFast.v
# set_global_assignment -name VERILOG_FILE ../build/verilog/mkInternalCalc_2024Aes2RoundPerCycle.v
# set_global_assignment -name VERILOG_FILE ../../../build/verilog/mkInternalCalc.v
# set_global_assignment -name VERILOG_FILE ../../../build/verilog/mkSimpleIOCapExposerV6_blockinvalid_Tb.v
    print(prefix, file=file)

    for verilog_file in glob.iglob("../build/verilog/*.v"):
        print(f"set_global_assignment -name VERILOG_FILE ../../{verilog_file}", file=file)

    suffix = f"""
set_global_assignment -name VERILOG_FILE ../../verilog/input_harness.v
set_global_assignment -name VERILOG_FILE ../../verilog/output_harness.v
set_global_assignment -name VERILOG_FILE {project_name}.v
set_global_assignment -name MIN_CORE_JUNCTION_TEMP 0
set_global_assignment -name MAX_CORE_JUNCTION_TEMP 100
set_global_assignment -name DEVICE 1SX280HU2F50E1VG
set_global_assignment -name FAMILY "Stratix 10"
set_global_assignment -name ERROR_CHECK_FREQUENCY_DIVISOR 256
set_location_assignment PIN_BF21 -to CLK_FAST -comment IOBANK_3C
set_instance_assignment -name IO_STANDARD "1.8 V" -to CLK_FAST -entity {project_name}
set_location_assignment PIN_BD19 -to CLK_SLOW -comment IOBANK_3C
set_instance_assignment -name IO_STANDARD "1.8 V" -to CLK_SLOW -entity {project_name}
set_instance_assignment -name IO_STANDARD "1.8 V" -to pin_out -entity {project_name}
set_instance_assignment -name IO_STANDARD "1.8 V" -to pin_in -entity {project_name}
set_instance_assignment -name IO_STANDARD "1.8 V" -to RST_N -entity {project_name}
set_location_assignment PIN_BJ19 -to pin_in -comment IOBANK_3C
set_location_assignment PIN_BH18 -to pin_out -comment IOBANK_3C
set_location_assignment PIN_BH20 -to RST_N -comment IOBANK_3C
set_global_assignment -name POWER_APPLY_THERMAL_MARGIN ADDITIONAL
set_instance_assignment -name PARTITION_COLOUR 4286709717 -to {project_name} -entity {project_name}
"""
    #set_global_assignment -name ALLOW_REGISTER_RETIMING OFF
    print(suffix, file=file)

    if seed is not None:
        print(f"set_global_assignment -name SEED {seed}", file=file)
        print(f"set_global_assignment -name PROJECT_OUTPUT_DIRECTORY output_files_{seed}", file=file)
    else:
        print("set_global_assignment -name PROJECT_OUTPUT_DIRECTORY output_files", file=file)

def qsf_from_null(project_name, dut, file):
    contents = f"""
set_global_assignment -name TOP_LEVEL_ENTITY {project_name}
set_global_assignment -name ORIGINAL_QUARTUS_VERSION 23.2.0
set_global_assignment -name PROJECT_CREATION_TIME_DATE "20:50:32  OCTOBER 16, 2025"
set_global_assignment -name LAST_QUARTUS_VERSION "23.2.0 Pro Edition"
set_global_assignment -name VERILOG_FILE ../../verilog/input_harness.v
set_global_assignment -name VERILOG_FILE ../../verilog/output_harness.v
set_global_assignment -name VERILOG_FILE ../../verilog/{dut}.v
set_global_assignment -name PROJECT_OUTPUT_DIRECTORY output_files
set_global_assignment -name MIN_CORE_JUNCTION_TEMP 0
set_global_assignment -name MAX_CORE_JUNCTION_TEMP 100
set_global_assignment -name DEVICE 1SX280HU2F50E1VG
set_global_assignment -name FAMILY "Stratix 10"
set_global_assignment -name ERROR_CHECK_FREQUENCY_DIVISOR 256
set_location_assignment PIN_BF21 -to CLK_FAST -comment IOBANK_3C
set_instance_assignment -name IO_STANDARD "1.8 V" -to CLK_FAST -entity {project_name}
set_location_assignment PIN_BD19 -to CLK_SLOW -comment IOBANK_3C
set_instance_assignment -name IO_STANDARD "1.8 V" -to CLK_SLOW -entity {project_name}
set_instance_assignment -name IO_STANDARD "1.8 V" -to pin_out -entity {project_name}
set_instance_assignment -name IO_STANDARD "1.8 V" -to pin_in -entity {project_name}
set_instance_assignment -name IO_STANDARD "1.8 V" -to RST_N -entity {project_name}
set_location_assignment PIN_BJ19 -to pin_in -comment IOBANK_3C
set_location_assignment PIN_BH18 -to pin_out -comment IOBANK_3C
set_location_assignment PIN_BH20 -to RST_N -comment IOBANK_3C
set_global_assignment -name POWER_APPLY_THERMAL_MARGIN ADDITIONAL
set_instance_assignment -name PARTITION_COLOUR 4286709717 -to {project_name} -entity {project_name}
"""
    print(contents, file=file)


def sdc(target_mhz: int, file):
    # target_mhz = target_hz / 10^6
    # target_hz = target_mhz * 10^6
    # clock_period_s = 1 / target_hz = (10^-6 / target_mhz)
    # clock_period_ns = clock_period_s * 10^9 = 10^3 / target_mhz
    clock_period_ns = 1000.0 / target_mhz

    contents = f"""
## Generated by gen_design.py

## Copyright (C) 2023  Intel Corporation. All rights reserved.
## Your use of Intel Corporation's design tools, logic functions 
## and other software and tools, and any partner logic 
## functions, and any output files from any of the foregoing 
## (including device programming or simulation files), and any 
## associated documentation or information are expressly subject 
## to the terms and conditions of the Intel Program License 
## Subscription Agreement, the Intel Quartus Prime License Agreement,
## the Intel FPGA IP License Agreement, or other applicable license
## agreement, including, without limitation, that your use is for
## the sole purpose of programming logic devices manufactured by
## Intel and sold by Intel or its authorized distributors.  Please
## refer to the applicable agreement for further details, at
## https://fpgasoftware.intel.com/eula.


## VENDOR  "Intel Corporation"
## PROGRAM "Quartus Prime"
## VERSION "Version 23.2.0 Build 94 06/14/2023 SC Pro Edition"

## DATE    "Fri Oct 17 14:26:22 2025"

##
## DEVICE  "1SX280HU2F50E1VG"
##


#**************************************************************
# Time Information
#**************************************************************

set_time_format -unit ns -decimal_places 3



#**************************************************************
# Create Clock
#**************************************************************

create_clock -name {{CLK_FAST}} -period {clock_period_ns:.3f} -waveform {{ 0.000 {clock_period_ns/2:.3f} }}  [get_ports CLK_FAST]
create_clock -name {{CLK_SLOW}} -period 10.000 -waveform {{ 0.000 5.000 }} [get_ports CLK_SLOW]


#**************************************************************
# Create Generated Clock
#**************************************************************



#**************************************************************
# Set Clock Latency
#**************************************************************



#**************************************************************
# Set Clock Uncertainty
#**************************************************************



#**************************************************************
# Set Input Delay
#**************************************************************



#**************************************************************
# Set Output Delay
#**************************************************************



#**************************************************************
# Set Clock Groups
#**************************************************************



#**************************************************************
# Set False Path
#**************************************************************

set_false_path -from [get_clocks {{CLK_FAST}}] -to [get_clocks {{CLK_SLOW}}]
set_false_path -from [get_clocks {{CLK_SLOW}}] -to [get_clocks {{CLK_FAST}}]

#**************************************************************
# Set Multicycle Path
#**************************************************************



#**************************************************************
# Set Maximum Delay
#**************************************************************



#**************************************************************
# Set Minimum Delay
#**************************************************************



#**************************************************************
# Set Input Transition
#**************************************************************


"""
    print(contents, file=file)

def justfile_from_bluespec(project_name, dut, file):
    contents = f"""project_name := "{project_name}"
dut := "{dut}"

default:
    @just --list

synth:
    cd ../../../ && make ./build/verilog/{{{{dut}}}}.v
    make ./output_files/{{{{project_name}}}}.sta.rpt

force-synth:
    cd ../../../ && make ./build/verilog/{{{{dut}}}}.v
    quartus_sh --flow compile {{{{project_name}}}}

force-synth-seeds:
    cd ../../../ && make ./build/verilog/{{{{dut}}}}.v
    quartus_sh -t ../../compile_revisions.tcl {{{{project_name}}}} 

reports:
    grep -B 1 -A 6 "; Fmax Summary" output_files/{{{{project_name}}}}.sta.rpt
    grep -B 1 -A 90 "; Fitter Resource Usage Summary" output_files/{{{{project_name}}}}.fit.place.rpt

gui:
    quartus {{{{project_name}}}}.qpf &

clean:
    rm -rf ./output_files/
    rm -rf ./qdb/
"""
    print(contents, file=file)

def justfile_from_null(project_name, dut, file):
    contents = f"""project_name := "{project_name}"
dut := "{dut}"

default:
    @just --list

synth:
    make ./output_files/{{{{project_name}}}}.sta.rpt

force-synth:
    quartus_sh --flow compile {{{{project_name}}}}

reports:
    grep -B 1 -A 6 "; Fmax Summary" output_files/{{{{project_name}}}}.sta.rpt
    grep -B 1 -A 90 "; Fitter Resource Usage Summary" output_files/{{{{project_name}}}}.fit.place.rpt

gui:
    quartus {{{{project_name}}}}.qpf &

clean:
    rm -rf ./output_files/
    rm -rf ./qdb/
"""
    print(contents, file=file)

def makefile_from_bluespec(project_name, dut, file):
    contents = f"""
# GNU flavored Makefile

project_name = {project_name}

basic_verilog_deps = ../../verilog/input_harness.v ../../verilog/output_harness.v $(project_name).v $(project_name).qpf $(project_name).qsf $(project_name).sdc
bluespec_generated_verilog_deps = $(wildcard ../../../build/verilog/*.v)
bsc_verilog_deps = $(wildcard $(BLUESPECDIR)/Verilog/*.v)
quartus_verilog_deps = $(wildcard ../../verilog/Verilog.Quartus/*.v)

.PRECIOUS: ./output_files/$(project_name).sta.rpt

./output_files/$(project_name).sta.rpt: $(basic_verilog_deps) $(bluespec_generated_verilog_deps) $(bsc_verilog_deps) $(quartus_verilog_deps)
	quartus_sh --flow compile $(project_name)
"""
    print(contents, file=file)

def makefile_from_null(project_name, dut, file):
    contents = f"""
# GNU flavored Makefile

project_name = {project_name}

basic_verilog_deps = ../../verilog/input_harness.v ../../verilog/output_harness.v ../../verilog/{dut}.v $(project_name).qpf $(project_name).qsf $(project_name).sdc

.PRECIOUS: ./output_files/$(project_name).sta.rpt

./output_files/$(project_name).sta.rpt: $(basic_verilog_deps)
	quartus_sh --flow compile $(project_name)
"""
    print(contents, file=file)

def overwrite_if_different(filename: Path, gen_contents: Callable[[TextIO], None]) -> None:
    contents = StringIO()
    gen_contents(contents)
    contents_str = contents.getvalue()

    if filename.is_file():
        with open(filename, "r", encoding="ascii") as f:
            if f.read() == contents_str:
                print(f"Not updating {filename}, it has the same contents")
                return
    
    with open(filename, "w", encoding="ascii") as f:
        f.write(contents_str)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("ifc", help=".txt file with the inputs/outputs of the interface")
    parser.add_argument("dut", help="the name of the design under test, should match a BSV file in ../testbenches/")
    parser.add_argument("target_mhz", type=int, help="target mhz value")
    parser.add_argument("--null-tb", action="store_true", help="If set, uses a null DUT named {dut} stored in ./verilog/ instead of a BSV file in ../testbenches")

    args = parser.parse_args()

    ifc = InterfaceSpec.generate(ifc_file_path=args.ifc)
    dut: str = args.dut
    target_mhz: int = args.target_mhz
    
    PROJECT_NAME = f"{dut}_{ifc.ifc_name}_design"

    PROJECT_FOLDER = Path("projects", f"{PROJECT_NAME}_{target_mhz}MHz")

    DUT_VERILOG_FILE = PROJECT_FOLDER / f"{PROJECT_NAME}.v"
    DUT_QPF_FILE = PROJECT_FOLDER / f"{PROJECT_NAME}.qpf"
    DUT_QSF_FILE = PROJECT_FOLDER / f"{PROJECT_NAME}.qsf"
    DUT_SDC_FILE = PROJECT_FOLDER / f"{PROJECT_NAME}.sdc"
    JUSTFILE = PROJECT_FOLDER / "Justfile"
    MAKEFILE = PROJECT_FOLDER / "Makefile"

    os.makedirs(PROJECT_FOLDER, exist_ok=True)

    # These are the same no matter if null_tb
    overwrite_if_different(DUT_VERILOG_FILE, lambda f: toplevel_verilog(ifc, dut, f))
    overwrite_if_different(DUT_QPF_FILE, lambda f: qpf(PROJECT_NAME, f))
    overwrite_if_different(DUT_SDC_FILE, lambda f: sdc(target_mhz, f))

    assert not args.null_tb
    # if args.null_tb:
    #     overwrite_if_different(DUT_QSF_FILE, lambda f: qsf_from_null(PROJECT_NAME, dut, f))
    #     overwrite_if_different(MAKEFILE, lambda f: makefile_from_null(PROJECT_NAME, dut, f))
    #     overwrite_if_different(JUSTFILE, lambda f: justfile_from_null(PROJECT_NAME, dut, f))
    # else:
    #     overwrite_if_different(DUT_QSF_FILE, lambda f: qsf_from_bluespec(PROJECT_NAME, f))
    #     overwrite_if_different(MAKEFILE, lambda f: makefile_from_bluespec(PROJECT_NAME, dut, f))
    #     overwrite_if_different(JUSTFILE, lambda f: justfile_from_bluespec(PROJECT_NAME, dut, f))

    overwrite_if_different(DUT_QSF_FILE, lambda f: qsf_from_bluespec(PROJECT_NAME, f))
    overwrite_if_different(MAKEFILE, lambda f: makefile_from_bluespec(PROJECT_NAME, dut, f))
    overwrite_if_different(JUSTFILE, lambda f: justfile_from_bluespec(PROJECT_NAME, dut, f))

    for seed in range(N_SEEDS):
        SEED_QSF_FILE = PROJECT_FOLDER / f"{seed_name(seed)}.qsf"
        SEED_SDC_FILE = PROJECT_FOLDER / f"{seed_name(seed)}.sdc"
        SEED_DESC = PROJECT_FOLDER / f"{seed_name(seed)}_description.txt"

        overwrite_if_different(SEED_QSF_FILE, lambda f: qsf_from_bluespec(PROJECT_NAME, f, seed=seed))
        overwrite_if_different(SEED_SDC_FILE, lambda f: sdc(target_mhz, f))
        overwrite_if_different(SEED_DESC, lambda f: print(f"seed = {seed}", file=f))