default:
    @just --list

gen ifc blu_design mhz:
    # Make the verilog, which ensures all the relevant files exist for the project generator
    (cd ../ && make ./build/verilog/{{blu_design}}.v)
    # Make the working directory for quartus
    uv run python3 gen_design.py {{ifc}} {{blu_design}} {{mhz}}

gen-all: \
    (gen "SimpleIOCapExposerKeyMngrV2Tb.txt" "mkSimpleIOCapExposerV6_blockinvalid_1percycle_Tb" "500") \
    (gen "SimpleIOCapExposerKeyMngrV2Tb.txt" "mkSimpleIOCapExposerV6_blockinvalid_Tb" "500") \
    (gen "SimpleIOCapExposerKeyMngrV2Tb.txt" "mkSimpleIOCapExposerV6_blockinvalid_1percycle_Tb" "200") \
    (gen "SimpleIOCapExposerKeyMngrV2Tb.txt" "mkSimpleIOCapExposerV6_blockinvalid_Tb" "200") \
    (gen "UnifiedSingleExposerKeyMngrTb.txt" "mkCombinedIOCapExposerV6_0pool_KeyManager2V1_Tb" "185") \
    (gen "UnifiedSingleExposerKeyMngrTb.txt" "mkCombinedIOCapExposerV6_blockinvalid_1pool_1percycle_KeyManager2V1_Tb" "185") \
    (gen "UnifiedSingleExposerKeyMngrTb.txt" "mkCombinedIOCapExposerV6_blockinvalid_2pool_1percycle_KeyManager2V1_Tb" "185") \
    (gen "UnifiedSingleExposerKeyMngrTb.txt" "mkCombinedIOCapExposerV6_blockinvalid_3pool_1percycle_KeyManager2V1_Tb" "185") \
    (gen "UnifiedSingleExposerKeyMngrTb.txt" "mkCombinedIOCapExposerV6_blockinvalid_4pool_1percycle_KeyManager2V1_Tb" "185") \
    (gen "UnifiedSingleExposerKeyMngrTb.txt" "mkCombinedIOCapExposerV6_blockinvalid_1pool_2percycle_KeyManager2V1_Tb" "185") \
    (gen "UnifiedSingleExposerKeyMngrTb.txt" "mkCombinedIOCapExposerV6_blockinvalid_2pool_2percycle_KeyManager2V1_Tb" "185") \
    (gen "UnifiedSingleExposerKeyMngrTb.txt" "mkCombinedIOCapExposerV6_blockinvalid_3pool_2percycle_KeyManager2V1_Tb" "185") \
    (gen "UnifiedSingleExposerKeyMngrTb.txt" "mkCombinedIOCapExposerV6_blockinvalid_4pool_2percycle_KeyManager2V1_Tb" "185") \
    (gen "UnifiedSingleExposerKeyMngrTb.txt" "mkCombinedIOCapExposerV6_blockinvalid_5pool_2percycle_KeyManager2V1_Tb" "185") \
    (gen "UnifiedSingleExposerKeyMngrTb.txt" "mkCombinedIOCapExposerV6_blockinvalid_9pool_1percycle_KeyManager2V1_Tb" "185") \
    (gen "UnifiedSingleExposerKeyMngr64Tb.txt" "mkCombinedIOCapExposerV6_0pool_KeyManager2V1_64_Tb" "200") \
    (gen "UnifiedSingleExposerKeyMngr64Tb.txt" "mkCombinedIOCapExposerV6_blockinvalid_1pool_2percycle_KeyManager2V1_64_Tb" "200") \
    (gen "UnifiedSingleExposerKeyMngr64Tb.txt" "mkCombinedIOCapExposerV6_blockinvalid_2pool_2percycle_KeyManager2V1_64_Tb" "200") \
    (gen "UnifiedSingleExposerKeyMngr64Tb.txt" "mkCombinedIOCapExposerV6_blockinvalid_3pool_2percycle_KeyManager2V1_64_Tb" "200") \
    (gen "UnifiedSingleExposerKeyMngr64Tb.txt" "mkCombinedIOCapExposerV6_blockinvalid_4pool_2percycle_KeyManager2V1_64_Tb" "200") \
    (gen "UnifiedSingleExposerKeyMngr64Tb.txt" "mkCombinedIOCapExposerV6_blockinvalid_5pool_2percycle_KeyManager2V1_64_Tb" "200") \
    (gen "SingleChecker3.txt" "mkSingleChecker3_1percycle" "200") \
    (gen "SingleChecker3.txt" "mkSingleChecker3_2percycle" "200") \
    (gen "SingleChecker3.txt" "mkSingleChecker3_1percycle" "300") \
    (gen "SingleChecker3.txt" "mkSingleChecker3_2percycle" "300") \
    (gen "SingleChecker3.txt" "mkSingleChecker3_null" "300") \

# gen-null:
#     uv run python3 gen_design.py "UnifiedSingleExposerKeyMngrTb.txt" "null_UnifiedSingleExposerKeyMngrTb" "200" --null-tb
#     uv run python3 gen_design.py "SingleChecker3.txt" "null_SingleChecker3" "300" --null-tb

resynth-paper-reports:
    # just projects/null_SingleChecker3_SingleChecker3_design_300MHz/force-synth-seeds
    # just projects/null_UnifiedSingleExposerKeyMngrTb_UnifiedSingleExposerKeyMngrTb_design_200MHz/force-synth-seeds

    just projects/mkSingleChecker3_null_SingleChecker3_design_300MHz/force-synth-seeds
    just projects/mkSingleChecker3_1percycle_SingleChecker3_design_300MHz/force-synth-seeds
    just projects/mkSingleChecker3_2percycle_SingleChecker3_design_300MHz/force-synth-seeds
    just projects/mkCombinedIOCapExposerV6_0pool_KeyManager2V1_64_Tb_UnifiedSingleExposerKeyMngr64Tb_design_200MHz/force-synth-seeds
    just projects/mkCombinedIOCapExposerV6_blockinvalid_1pool_2percycle_KeyManager2V1_64_Tb_UnifiedSingleExposerKeyMngr64Tb_design_200MHz/force-synth-seeds
    just projects/mkCombinedIOCapExposerV6_blockinvalid_2pool_2percycle_KeyManager2V1_64_Tb_UnifiedSingleExposerKeyMngr64Tb_design_200MHz/force-synth-seeds
    just projects/mkCombinedIOCapExposerV6_blockinvalid_3pool_2percycle_KeyManager2V1_64_Tb_UnifiedSingleExposerKeyMngr64Tb_design_200MHz/force-synth-seeds
    just projects/mkCombinedIOCapExposerV6_blockinvalid_4pool_2percycle_KeyManager2V1_64_Tb_UnifiedSingleExposerKeyMngr64Tb_design_200MHz/force-synth-seeds
    just projects/mkCombinedIOCapExposerV6_blockinvalid_5pool_2percycle_KeyManager2V1_64_Tb_UnifiedSingleExposerKeyMngr64Tb_design_200MHz/force-synth-seeds

    just regen-paper-reports

regen-paper-reports:
    uv run python3 gen_report.py ./results/ ./hardware_synths.toml