# Very simple makefile that pulls in the right include directories for any testbenches
# and builds Bluesim versions.

BUILDDIR = ./build
BUILDDIR_NOTABLEHEADERS = ./build_notable/

BLUESTUFFDIR = ../Toooba/libs/BlueStuff
include $(BLUESTUFFDIR)/bluestuff.inc.mk
BSVPATH = +:$(BLUESTUFF_DIRS):./aes:./cap2024:./testbenches:./util:../AxiWindow

BSCFLAGS = -bdir $(BUILDDIR) -info-dir $(BUILDDIR) -simdir $(BUILDDIR) -vdir $(BUILDDIR)/verilog -p $(BSVPATH) -u -aggressive-conditions -D KANATA +RTS -K512M -RTS 

BSCDIR = $(dir $(shell which bsc))../

$(BUILDDIR)/%.bsim: ./testbenches/%.bsv alwaysRemake
	mkdir -p $(BUILDDIR)
	bsc $(BSCFLAGS) -sim -g $* $< 
	bsc $(BSCFLAGS) -sim -e $* $@

.PRECIOUS: $(BUILDDIR)/verilog/%.v

$(BUILDDIR)/verilog/%.v: ./testbenches/%.bsv alwaysRemake
	mkdir -p $(BUILDDIR) $(BUILDDIR)/verilog
	bsc $(BSCFLAGS) -verilog -g $* -u $<

$(BUILDDIR)/%.vsim: $(BUILDDIR)/verilog/%.v ./testbenches/%.cpp ./testbenches/librust_caps_c/librust_caps_c.a alwaysRemake
	verilator --Mdir $(BUILDDIR) --no-timing --trace --top-module $* --cc --build --exe -CFLAGS -g -CFLAGS -std=gnu++20 -CFLAGS -I../testbenches/include -CFLAGS -I../testbenches/librust_caps_c -CFLAGS -fno-var-tracking-assignments -o $*.vsim -I$(BSCDIR)lib/Verilog/ $(BSCDIR)lib/Verilator/verilator_config.vlt $(shell echo $(BUILDDIR)/verilog/*.v) ./testbenches/$*.cpp $(shell pwd)/testbenches/librust_caps_c/librust_caps_c.a
	mkdir -p $(BUILDDIR_NOTABLEHEADERS)
	cp $(BUILDDIR)/V$*.h $(BUILDDIR_NOTABLEHEADERS)

.PHONY: list alwaysRemake

list:
	@printf "Available targets:\n\tclean\n\tclean-vsim\n\t$(BUILDDIR)/%%.bsim\n\t$(BUILDDIR)/verilog/%%.v\n\t$(BUILDDIR)/%%.vsim\n"
	
clean:
	rm -rf $(BUILDDIR)

clean-vsim:
	rm $(BUILDDIR)/*.vsim

alwaysRemake: