
// Generated by gen_design.py from UnifiedSingleExposerKeyMngr64Tb.txt
// Expects mkCombinedIOCapExposerV6_blockinvalid_2pool_2percycle_KeyManager2V1_64_Tb to fit the UnifiedSingleExposerKeyMngr64Tb Bluespec interface
module mkCombinedIOCapExposerV6_blockinvalid_2pool_2percycle_KeyManager2V1_64_Tb_UnifiedSingleExposerKeyMngr64Tb_design(
    input CLK_SLOW,
    input CLK_FAST,
    input RST_N,
    input pin_in,
    output pin_out
);
    wire[401-1:0] dut_in;
    wire[512-1:0] dut_out;
    assign dut_out[511:381] = 0;
    
    input_harness#(.BITS(401)) i(
        .slow_clk(CLK_SLOW),
        .fast_clk(CLK_FAST),
        .rst_n(RST_N),
        .pin_on_slow_clk(pin_in),
        .data_on_fast_clk(dut_in)
    );

    output_harness#(.BITS(512), .LG_BITS(9)) o(
        .slow_clk(CLK_SLOW),
        .fast_clk(CLK_FAST),
        .rst_n(RST_N),
        .data_on_fast_clk(dut_out),
        .pin_on_slow_clk(pin_out)
    );

    mkCombinedIOCapExposerV6_blockinvalid_2pool_2percycle_KeyManager2V1_64_Tb dut(
        .CLK(CLK_FAST),
        .RST_N(RST_N),

        .keyStore_ar_put_val(dut_in[15:0]),
        .keyStore_aw_put_val(dut_in[31:16]),
        .exposer4x32_iocapsIn_axiSignals_w_put_val(dut_in[68:32]),
        .exposer4x32_sanitizedOut_r_put_val(dut_in[107:69]),
        .exposer4x32_sanitizedOut_b_put_val(dut_in[113:108]),
        .keyStore_w_put_val(dut_in[185:114]),
        .exposer4x32_iocapsIn_axiSignals_ar_put_val(dut_in[285:186]),
        .exposer4x32_iocapsIn_axiSignals_aw_put_val(dut_in[385:286]),
        .EN_exposer4x32_iocapsIn_axiSignals_ar_put(dut_in[386]),
        .EN_exposer4x32_iocapsIn_axiSignals_aw_put(dut_in[387]),
        .EN_exposer4x32_iocapsIn_axiSignals_b_drop(dut_in[388]),
        .EN_exposer4x32_iocapsIn_axiSignals_r_drop(dut_in[389]),
        .EN_exposer4x32_iocapsIn_axiSignals_w_put(dut_in[390]),
        .EN_exposer4x32_sanitizedOut_ar_drop(dut_in[391]),
        .EN_exposer4x32_sanitizedOut_aw_drop(dut_in[392]),
        .EN_exposer4x32_sanitizedOut_b_put(dut_in[393]),
        .EN_exposer4x32_sanitizedOut_r_put(dut_in[394]),
        .EN_exposer4x32_sanitizedOut_w_drop(dut_in[395]),
        .EN_keyStore_ar_put(dut_in[396]),
        .EN_keyStore_aw_put(dut_in[397]),
        .EN_keyStore_b_drop(dut_in[398]),
        .EN_keyStore_r_drop(dut_in[399]),
        .EN_keyStore_w_put(dut_in[400]),
        .keyStore_b_peek(dut_out[1:0]),
        .exposer4x32_sanitizedOut_w_peek(dut_out[38:2]),
        .exposer4x32_iocapsIn_axiSignals_r_peek(dut_out[77:39]),
        .exposer4x32_iocapsIn_axiSignals_b_peek(dut_out[83:78]),
        .keyStore_r_peek(dut_out[149:84]),
        .exposer4x32_sanitizedOut_ar_peek(dut_out[246:150]),
        .exposer4x32_sanitizedOut_aw_peek(dut_out[343:247]),
        .exposer4x32_iocapsIn_axiSignals_ar_canPut(dut_out[344]),
        .exposer4x32_iocapsIn_axiSignals_aw_canPut(dut_out[345]),
        .exposer4x32_iocapsIn_axiSignals_b_canPeek(dut_out[346]),
        .exposer4x32_iocapsIn_axiSignals_r_canPeek(dut_out[347]),
        .exposer4x32_iocapsIn_axiSignals_w_canPut(dut_out[348]),
        .exposer4x32_sanitizedOut_ar_canPeek(dut_out[349]),
        .exposer4x32_sanitizedOut_aw_canPeek(dut_out[350]),
        .exposer4x32_sanitizedOut_b_canPut(dut_out[351]),
        .exposer4x32_sanitizedOut_r_canPut(dut_out[352]),
        .exposer4x32_sanitizedOut_w_canPeek(dut_out[353]),
        .keyStore_ar_canPut(dut_out[354]),
        .keyStore_aw_canPut(dut_out[355]),
        .keyStore_b_canPeek(dut_out[356]),
        .keyStore_r_canPeek(dut_out[357]),
        .keyStore_w_canPut(dut_out[358]),
        .RDY_exposer4x32_iocapsIn_axiSignals_ar_put(dut_out[359]),
        .RDY_exposer4x32_iocapsIn_axiSignals_aw_put(dut_out[360]),
        .RDY_exposer4x32_iocapsIn_axiSignals_b_drop(dut_out[361]),
        .RDY_exposer4x32_iocapsIn_axiSignals_b_peek(dut_out[362]),
        .RDY_exposer4x32_iocapsIn_axiSignals_r_drop(dut_out[363]),
        .RDY_exposer4x32_iocapsIn_axiSignals_r_peek(dut_out[364]),
        .RDY_exposer4x32_iocapsIn_axiSignals_w_put(dut_out[365]),
        .RDY_exposer4x32_sanitizedOut_ar_drop(dut_out[366]),
        .RDY_exposer4x32_sanitizedOut_ar_peek(dut_out[367]),
        .RDY_exposer4x32_sanitizedOut_aw_drop(dut_out[368]),
        .RDY_exposer4x32_sanitizedOut_aw_peek(dut_out[369]),
        .RDY_exposer4x32_sanitizedOut_b_put(dut_out[370]),
        .RDY_exposer4x32_sanitizedOut_r_put(dut_out[371]),
        .RDY_exposer4x32_sanitizedOut_w_drop(dut_out[372]),
        .RDY_exposer4x32_sanitizedOut_w_peek(dut_out[373]),
        .RDY_keyStore_ar_put(dut_out[374]),
        .RDY_keyStore_aw_put(dut_out[375]),
        .RDY_keyStore_b_drop(dut_out[376]),
        .RDY_keyStore_b_peek(dut_out[377]),
        .RDY_keyStore_r_drop(dut_out[378]),
        .RDY_keyStore_r_peek(dut_out[379]),
        .RDY_keyStore_w_put(dut_out[380]),
        .debugKeyState__read(),
        .debugBadRead__read(),
        .debugBadWrite__read(),
        .debugGoodRead__read(),
        .debugGoodWrite__read(),
        .debugEnableKey__read(),
        .debugKillKey__read(),
        .RDY_debugBadRead__read(),
        .RDY_debugBadWrite__read(),
        .RDY_debugEnableKey__read(),
        .RDY_debugGoodRead__read(),
        .RDY_debugGoodWrite__read(),
        .RDY_debugKeyState__read(),
        .RDY_debugKillKey__read()
    );
endmodule

